version: "3.0"

tasks:
  mocks:
    cmds:
      - mockery
  tests:
    cmds:
      - go test -v ./... | grep -v "\[no test files\]"
  build:
    deps:
      - tests
    desc: "Build the project"
    cmds:
      - go build -o bin/kli ./*.go
