name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.0
    -
      name: Build kli
      id: build_kli
      run: |
        go test -v ./... | grep -v "\[no test files\]"
        go build -o bin/kli ./*.go
    -
      uses: actions/upload-artifact@v4
      with:
        name: kli
        path: bin/kli
  check_tag:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.check_tag.outputs.tag_exists }}
    steps:
    -
      name: Download kli
      uses: actions/download-artifact@v4
      with:
        name: kli
        path: bin/kli
    -
      name: Install kli
      run: |
        chmod +x bin/kli
    -
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Check tag
      id: check_tag
      run: |
        LATEST_VERSION=$( ./bin/kli semver )
        LATEST_GIT_TAG=$( git describe --tags --abbrev=0 )
        if [ "$LATEST_VERSION" == "$LATEST_GIT_TAG" ]; then
          echo "tag_exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "tag_exists=false" >> "$GITHUB_OUTPUT"
        fi
  create_tag:
    needs: check_tag
    runs-on: ubuntu-latest
    if: needs.check_tag.outputs.tag_exists == 'false'
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    -
      name: Download kli
      uses: actions/download-artifact@v4
      with:
        name: kli
        path: bin/kli
    -
      name: Install kli
      run: |
        chmod +x bin/kli
    -
      name: Push tags if needed
      id: push_tags
      run: |
        ./bin/kli semver -t -v